language: r
dist: trusty
sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
    - libudunits2-dev

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - Rscript -e 'blogdown::build_site()'

after_success:
  - travispush.sh
