language: r
dist: trusty
sudo: required

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - Rscript -e 'devtools::install_deps()'
  - Rscript -e 'blogdown::install_hugo()'

#script:
#  - Rscript -e 'blogdown::build_site()'

#after_success:
#  - travispush.sh
