language: r
dist: trusty
sudo: required

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes protobuf-compiler libprotobuf-dev libv8-3.14-dev libproj-dev libgeos-dev libgdal-dev libudunits2-dev
  
r_github_packages:
  - rstudio/blogdown
  - reconhub/outbreaks
  - reconhub/epimaps
  - reconhub/incidence
  - tidyverse/ggplot2


cache:
  packages: yes

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - Rscript -e 'blogdown::build_site()'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh travispush.sh; fi'
